### ISSUE TITLE
after waking up from screen saver, the system trackpad gesture does not work

### ISSUE THREAD

**Issue by idhun90** [aaronkollasch/jitouch#11]
The trackpad gesture does not work intermittently after waking up from the screen saver. It works when I wake up after operating the screen saver again.

Is there a way to check if it collides with Jitouch?

**Comment by aaronkollasch** [comment]
Thanks for reporting this, I will look further when I have the time.

**Comment by aaronkollasch** [comment]
Hi, are you still experiencing this issue?

**Comment by idhun90** [comment]
At some point, I haven't experienced any related problems. Thank you for your reply.

**Comment by aaronkollasch** [comment]
Ok, great. I will close this issue for now but feel free to reopen if it shows up again.

**Comment by aaronkollasch** [comment]
Hmm, I'm not sure. Do you know how long the screen saver has to remain active for the issue to happen?

**Comment by idhun90** [comment]
The question you asked is not accurate. Sometimes, even if the screen saver is shut down immediately, it does not work, and other times, it may work even if it is maintained for a long time.


> 2022. 10. 8. 오전 3:00, Aaron Kollasch ***@***.***> 작성:
> 
> Hmm, I'm not sure. Do you know how long the screen saver has to remain active for the issue to happen?

**Comment by aaronkollasch** [comment]
Ok, I tried this a few times and sometimes got into a state where the gestures wouldn't work immediately after unlocking from a screen saver. However, I think this is because the lock screen still had focus, so even keyboard shortcuts to switch tabs didn't work until I clicked on the current window to focus it. The gestures were still being recognized even if the actions weren't working. Does your issue go away after clicking on a window or switching windows?

**Comment by idhun90** [comment]
I'll test that part at home. The test is difficult because I don't have a Mac in my hand. I will reply after checking.


> 2022. 10. 9. 오후 2:36, Aaron Kollasch ***@***.***> 작성:
> 
> Ok, I tried this a few times and sometimes got into a state where the gestures wouldn't work immediately after unlocking from a screen saver. However, I think this is because the lock screen still had focus, so even keyboard shortcuts to switch tabs didn't work until I clicked on the current window to focus it. The gestures were still being recognized even if the actions weren't working. Does your issue go away after clicking on a window or switching windows?
> 
>
