### ISSUE TITLE
Doesn't work on Monterey 12.2

### ISSUE THREAD

**Issue by ApolloMars** [aaronkollasch/jitouch#16]
I installed the latest version of 2.79, but it doesn’t seem functional. None of the gestures is workable.

**Comment by aaronkollasch** [comment]
Thanks for the heads up. I'll get back to you if I have a fix.

**Comment by cristigoia** [comment]
I'm on Monterey 12.0.1 and same, can install but can't open the pref pane like so: https://ibb.co/vHZbJr9

**Comment by aaronkollasch** [comment]
@cristigoia That's surprising as the most recent versions were developed on 12.0.1. Could you make a separate issue, and include info on what system you're running it on, and the Jitouch version?

**Comment by aaronkollasch** [comment]
@ApolloMars I've updated to Monterey 12.2.1 and my gestures are working fine. Can you check that Jitouch is allowed in System Preferences -> Security & Privacy -> Privacy -> Accessibility?

**Comment by cristigoia** [comment]
I've also updated to 12.2.1 right after I wrote the previous comment. The problem still persists and I don't see jitouch in the Accessibility. Can't add it manually as it's grayed out (https://ibb.co/br87xrM) from ~/username/Library/PreferencePanes .

**Comment by cristigoia** [comment]
I've updated to 12.2.1 after my previous comment and now seems to work just fine after adding it to the Accessibility manually as you mentioned in a previous issue (https://github.com/aaronkollasch/jitouch/issues/9#issuecomment-988942559). Also did create the LaunchAgents folder (don't know if this matters but did it). Thank you @aaronkollasch! You're a life savior! <3

**Comment by sangyoo91** [comment]
Not working for me. Maybe I'm doing something wrong but I've followed all directions.

I'm on MBP M1 Max 14inch Monterey 12.2

**Comment by aaronkollasch** [comment]
I'm not able to test with 12.2 but perhaps there's a bug in 12.2 that's fixed in 12.2.1? Can you check `~/Library/Logs/com.jitouch.Jitouch.log`?

**Comment by DongGilKim** [comment]
Hello,

> Thanks for the heads up. I'll get back to you if I have a fix.

Hello,

Mine does not work too. I can install but I need to command in terminal "/Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch" to execute Jitouch. Once I close the terminal, Jitouch again does not work. So do I need to command everytime I use Jitouch?

**Comment by skidevil91** [comment]
Just upgraded to the Macbook Pro with M1 chip, and trying like crazy to get Jitouch to work. I'm on Monterey 12.4, and using Jitouch 2.74.

I can actually get it to load, using the below terminal command, but whenever I mouse over any of the preferences to change them it quits on me.

I see reference to Jitouch v 2.79 - is there an updated version available? 

Any help appreciated - I can't live without it!

*********
THIS IS THE TERMINAL COMMAND THAT ALLOWS ME TO OPEN IT
pkill -f "Jitouch"
sleep 5
nohup ~/Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch > /dev/null 2>&1 &

**Comment by aaronkollasch** [comment]
@skidevil91 Jitouch 2.74 predates my releases and is definitely not compatible with M1 Macs or macOS 12.

Try Jitouch v2.79 at the [releases](https://github.com/aaronkollasch/jitouch/releases) page. There is also a beta release for v2.80. Let me know if those aren't working with macOS 12.4.

**Comment by DongGilKim** [comment]
Glad that you got somehow working the jitouch. Arron I think skidevil91 also had the same issue with me. skidevil91, do you also need to type 
> /Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch 

to execute Jitouch every time?

**Comment by skidevil91** [comment]
no. here's the entire sequence i have to do:

first have to type:
sudo -s

then enter comp password

then i paste this:

pkill -f "Jitouch"
sleep 5
nohup
~/Library/PreferencePanes/Jitouch.prefPane/Contents/Resources/Jitouch.app/Contents/MacOS/Jitouch
> /dev/null 2>&1 &

then I open up jitouch and toggle it off and then on. after that, it seems
to work.

**Comment by aaronkollasch** [comment]
It shouldn't be necessary to run Jitouch as root (in fact I don't recommend it), and launchctl should take care of running the Jitouch executable in the background.

Since this seems to be a recurring issue, can one of you start a new issue relating to Jitouch not running by itself?

**Comment by skidevil91** [comment]
Soo...I'm actually fairly new to github and only signed up since I saw this
discussion and needed a solve for Jitouch. I'd love to be kept in the loop
thought to understand (in somewhat laymans terms?) what I could/should be
doing to run this better.

**Comment by aaronkollasch** [comment]
I'm going to close this issue but for those interested in getting Jitouch to run automatically we can continue in issue #23.
