### ISSUE TITLE
System UI freeze after "Two-fix Middle-Double-Tap" to close tabs

### ISSUE THREAD

**Issue by soqt** [aaronkollasch/jitouch#20]
Everytime after I restart my macbook, and try to use "Two-fix Middle-Double-Tap" to close tabs, there is a chance that my computer interface will get freeze (but I can launch Mission Control or App Expose by gesture pad). It happens mostly only once after rebooting system. And after a few seconds, the UI will be back to normal. I currently only found this situation by this sepecific gesture.

System: MacOS Monterey 12.3.1
Chip: Apple M1 Max

**Comment by aaronkollasch** [comment]
Hi, thanks for reporting. I just tried the gesture and couldn't get it to reproduce. Could be a tricky bug.

Could you check the contents of the log file at `~/Library/Logs/com.jitouch.Jitouch.log`? Do you see any error messages that don't look like these lines:
```
2022-05-08 19:04:37.447 Jitouch[1044:9631] Initializing.
2022-05-08 19:04:37.449 Jitouch[1044:9631] Start device 0 144115188075855919 family 105 (not running)
2022-05-08 19:04:37.449 Jitouch[1044:9631] Device 0 144115188075855919 family 105 is running
2022-05-08 19:47:07.103 Jitouch[1044:9631] Woke up.
2022-05-08 19:47:07.104 Jitouch[1044:9631] Reloading gestures.
2022-05-08 19:47:07.104 Jitouch[1044:9631] Stop device 0 144115188075855919 family 105 (running)
2022-05-08 19:47:07.117 Jitouch[1044:9631] Device 0 144115188075855919 family 105 is not running
2022-05-08 19:47:08.133 Jitouch[1044:9631] Start device 0 144115188075855919, family 105 (not running)
2022-05-08 19:47:08.134 Jitouch[1044:9631] Device 0 144115188075855919 family 105 is running
```

The temporary UI freeze means one of the UI callback functions is not responding, possibly the `gestureTrackpadTwoFixOneDoubleTap` function, perhaps the `doCommand` inside of that, as I don't see much possibility for an infinite loop or other hang in that function. The hang only gets broken when the system sends a timeout signal to Jitouch, which resets the eventTap, allowing inputs to pass through.

**Comment by soqt** [comment]
I found some error messages like this: 
`2022-04-30 08:55:18.025 Jitouch[644:5656] Woke up.
2022-04-30 08:55:18.025 Jitouch[644:5656] Reloading gestures.
2022-04-30 08:55:18.025 Jitouch[644:5656] Stop device 0 144115188075855919 family 105 (running)
2022-04-30 08:55:18.027 Jitouch[644:5656] Device 0 144115188075855919 family 105 is not running
2022-04-30 08:55:19.041 Jitouch[644:5656] Start device 0 144115188075855919, family 105 (not running)
2022-04-30 08:55:19.041 Jitouch[644:5656] Device 0 144115188075855919 family 105 is running
2022-04-30 08:55:19.052 Jitouch[644:5656] Received kCGEventTapDisabledByTimeout; attempting to recreate CGEventTap. Allow Jitouch in System Preferences -> Privacy -> Accessibility.
2022-04-30 08:55:20.089 Jitouch[644:5656] CGEventTap created`

However, I have both Jitouch & System Preference allowed in Accessibility all the time. My jitouch version is 2.79

**Comment by soqt** [comment]
I just reproduced this error. I have twitter installed. (Version 19.9.6 from app store). After rebooting the system, if I launch twitter and close it by  "Two-fix Middle-Double-Tap", my UI freezes immediately.

**Comment by aaronkollasch** [comment]
Ok, I'll try that later. The freeze shouldn't be related to the Accessibility preference as the other gestures are working and the freeze only happens occassionally.

**Comment by aaronkollasch** [comment]
Within `gestureTrackpadTwoFixOneDoubleTap` https://github.com/aaronkollasch/jitouch/blob/c722b388ee3e9eada1fc451a84a80fb8246a63cb/jitouch/Jitouch/Gesture.m#L1688
the only potentially blocking code is in the call to `doCommand`
https://github.com/aaronkollasch/jitouch/blob/c722b388ee3e9eada1fc451a84a80fb8246a63cb/jitouch/Jitouch/Gesture.m#L557

`doCommand` does a lot of things that might hang, so it should be run in a separate thread, not the callback thread. I'll change that when I get the chance, and it'll probably fix this and other issues (#18).

**Comment by aaronkollasch** [comment]
Ok, so I tried running `doCommand` in a separate thread and it didn't fix this issue. I think I found the problem though. Here's the summary for future reference:

It appears that the freeze is the result of a race condition between two different API's callbacks: the `MTRegisterContactFrameCallback` function `trackpadCallback`:
https://github.com/aaronkollasch/jitouch/blob/572bed758e6d38b0671a1b53f2d269539c21cfde/jitouch/Jitouch/Gesture.m#L1823
and the `CGEventTap` callback function `CGEventCallback`:
https://github.com/aaronkollasch/jitouch/blob/572bed758e6d38b0671a1b53f2d269539c21cfde/jitouch/Jitouch/Gesture.m#L2661

Within `trackpadCallback`, `gestureTrackpadOneFixOneTap` sets the variable `twoFingersDistance`:
https://github.com/aaronkollasch/jitouch/blob/572bed758e6d38b0671a1b53f2d269539c21cfde/jitouch/Jitouch/Gesture.m#L1397-L1401

And, in `CGEventCallback`, a MouseUp or MouseDown event is dropped if two fingers are down and `twoFingersDistance` is < 0.3.
https://github.com/aaronkollasch/jitouch/blob/572bed758e6d38b0671a1b53f2d269539c21cfde/jitouch/Jitouch/Gesture.m#L2662-L2664

So to perform a "Two-fix Middle-Double-Tap", two fingers are held down and a third is tapped, so `gestureTrackpadOneFixOneTap` sets `twoFingersDistance` to 100. A MouseDown event is registered with 3 fingers, so it is not dropped. The system considers the mouse to be down. Then when the third finger lifts, a MouseUp event may be registered. 

Now, if CGEventCallback sees the lift first, the MouseUp event goes through. But, if `trackpadCallback` sees the lift first, it sets `twoFingersDistance` < 0.3, and then CGEventCallback drops the MouseUp event. So, the system considers the mouse to be held down, until you click again. This causes issues in the UI's responsiveness to mouse movement.

**reproducing the issue**
Do a "Two-fix Middle-Tap" while your cursor is inside a text window, then move the cursor. Within a few tries the cursor should highlight text as if the mouse is down.

**solutions**
If I remove the mouse event-dropping code from `CGEventCallback`, the problem goes away. However, this code is still useful as it is intended to "suppress left click in next/prev tab gesture", which could get annoying rather quickly. The problem could be solved by allowing MouseUp but not MouseDown – inadvertent MouseUps are much less likely to cause issues.

**Comment by aaronkollasch** [comment]
Hi, I merged the pull request and will release a beta version of Jitouch with the changes soon. Let me know if the problem persists and I'll reopen the issue.

**Comment by aaronkollasch** [comment]
The beta release is available here: https://github.com/aaronkollasch/jitouch/releases/tag/v2.80-beta.1

**Comment by soqt** [comment]
Awesome! Downloaded the new version and the bug is fixed. Thank you so much for providing such an aweosome Jitouch Macbook solution!

**Comment by aaronkollasch** [comment]
Glad to hear it!
