### ISSUE TITLE
[feature request]Please Support 4 finger tap

### ISSUE THREAD

**Issue by moranno** [aaronkollasch/jitouch#25]
Please Support 4 finger tap
Thanks in advance.

**Comment by aaronkollasch** [comment]
Hi, I've added a PR #38 that will fix this issue. It is a bit tricky, however, since index-to-pinky and pinky-to-index gestures could also be interpreted as four-finger taps. I think the PR is at a point where index-to-pinky will work as normal while adding four-finger tap.

**Comment by aaronkollasch** [comment]
Here is a debug build to try out that supports this feature. I'll be testing this for a bit.
[Install-Jitouch.pkg.zip](https://github.com/aaronkollasch/jitouch/files/9643783/Install-Jitouch.pkg.zip)
