### ISSUE TITLE
Magic Trackpad right click

### ISSUE THREAD

**Issue by gieljnssns** [aaronkollasch/jitouch#26]
I wan't to enable right click on a magic trackpad (macbook pro 14") with 3 finger click, but this isn't an option.
<img width="695" alt="Schermafbeelding 2022-08-02 om 04 01 15" src="https://user-images.githubusercontent.com/17234951/182275937-871011b2-ba62-4768-a313-d57096f3c02d.png">

**Comment by aaronkollasch** [comment]
Hello,
It's possible to add "Right Click" to the actions menu, but I'm not sure it's necessary. On my MBP 16", with the "Three-Finger Click" gesture disabled, clicking with three fingers already performs a right-click.

**Comment by gieljnssns** [comment]
What settings do you use in system preferences?
With my macbook nothing happens when using 3 finger click
<img width="688" alt="Schermafbeelding 2022-08-04 om 22 53 56" src="https://user-images.githubusercontent.com/17234951/182951011-efc556dc-5c69-4bc0-b068-80f9f05b558c.png">
<img width="695" alt="Schermafbeelding 2022-08-04 om 22 54 09" src="https://user-images.githubusercontent.com/17234951/182951014-b25a9235-e44b-44eb-8321-b8c274c6dc5f.png">
<img width="696" alt="Schermafbeelding 2022-08-04 om 22 54 23" src="https://user-images.githubusercontent.com/17234951/182951020-a04d5890-774f-4538-98de-416cb56f71a8.png">

**Comment by aaronkollasch** [comment]
I have secondary click with two fingers enabled, and it enables both two and three finger right click.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/7785912/182951346-3654becb-d4e1-4025-a587-455b75b2bd2d.png">

**Comment by gieljnssns** [comment]
I'm sorry, but when I enable 2 finger click my macbook only does right click with 2 fingers, not 3.

**Comment by aaronkollasch** [comment]
Weird, I reloaded Jitouch and lost the 3-finger right click for a while, and 3-finger right clicks only work sporadically now. Not sure why the left and right click actions are confined to the Magic Mouse but I could see about enabling them. Is there a reason why two-finger right clicks aren't good enough?

**Comment by gieljnssns** [comment]
I use 3 finger click more then 5 years on my magic mouse and on my old macbook. So it is just an habit. 
At first i was using bettertouchtool but when I reinstalled them (clean install) I lost my license and now I found jtouch...

**Comment by gieljnssns** [comment]
Sorry to bother you again. 
Is it possible to make a brew cask of your version of jitouch?
The original has one, but it isn't maintained anymore. 

I use a brewfile to install all my software so I can add it to that file. 
https://formulae.brew.sh/cask/jitouch#default
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/jitouch.rb

And this is an example of a cask installed with a .pkg
https://github.com/Homebrew/homebrew-cask/commit/da1a813e96f90fdf17180784c87130b2aad969f3

**Comment by aaronkollasch** [comment]
I just made a brew cask at https://github.com/aaronkollasch/homebrew-tap/blob/main/Casks/jitouch.rb
You should be able to install with this line in your brewfile: `cask "aaronkollasch/tap/jitouch"`

One issue is that you can't specify whether to install for all users or just the current user. It seems to install for all users by default.
Also, the prefpane needs to be opened on first install to actually start the Jitouch agent.

**Comment by gieljnssns** [comment]
Is the trackpad tight click branch included?

**Comment by aaronkollasch** [comment]
Just merged the right click branch, so it will be included in the next release.

**Comment by gieljnssns** [comment]
Thanks a lot
