### ISSUE TITLE
Gestures stop working after trackpad re-connection

### ISSUE THREAD

**Issue by hw0603** [aaronkollasch/jitouch#28]
I'm using a Mac Mini M1, Monterey 12.5.

jitouch automatically launches successfully when I restart my Mac, but when the Magic Trackpad is disconnected and reconnected, the gestures set on jitouch do not work.

The only way to get the gestures to work again is to close the program and restart jitouch in preferences.
Is this an intended feature? If not, what can I do to fix this bug?

I've tried v2.79, v2.80, and v2.81, but no good

**Comment by aaronkollasch** [comment]
Yeah I've seen this issue as well recently. Jitouch should detect when the Magic Trackpad is attached/detached but perhaps the internal identifiers have changed.

Specifically, this code should add the listener:
https://github.com/aaronkollasch/jitouch/blob/9a8d9009a639254e447d6727a4785453eb12d362/jitouch/Jitouch/Gesture.m#L3006-L3019

I'll see about fixing it when I get the chance.

**Comment by aaronkollasch** [comment]
In the mean time, you can also use the terminal command `killall -HUP Jitouch` to send a signal to Jitouch to reload its devices without restarting. 
Or, `killall Jitouch` will quit Jitouch and then the LaunchAgent will restart it.

**Comment by shp7724** [comment]
I've been experiencing this issue recently as well. The thing is, my magic trackpad is always connected to the mac via cable, and I saw it in the middle of active usage of the trackpad. So I don't think this happens only on reconnections.

**Comment by aaronkollasch** [comment]
Hmm, that's weird. What happens if you run `killall -HUP Jitouch`, does it start working again? Also, can you check the log at `~/Library/Logs/com.jitouch.Jitouch.log` if that happens?

**Comment by aaronkollasch** [comment]
Hey, I've made a pull request that should fix this issue. Try out the debug build below and let me know how it goes.

[Install-Jitouch.pkg.zip](https://github.com/aaronkollasch/jitouch/files/9993844/Install-Jitouch.pkg.zip)
