### ISSUE TITLE
Three finger swipe with firefox

### ISSUE THREAD

**Issue by samcarter** [aaronkollasch/jitouch#45]
First of all: Thanks a lot for your bug fixes. I couldn't get the upstream version of jitouch to work on my M1 mac, but with your modifications it finally worked!

I'm using jitouch to remap the left/right three finger swipe to a specific keyboard shortcut. This works great in all apps with the one exception of firefox. If I change the gesture to something else, e.g. a three finger tap, the remapping will also work in firefox.

Do you happen to know why the three finger swipe does not work in firefox? I thought that maybe firefox monopolises the gesture, so I tried to disable everything in firefox about:config which looked related to gestures, but the there finger swipe still does not work.

<img width="1438" alt="Screenshot 2022-11-04 at 17 23 12" src="https://user-images.githubusercontent.com/43832342/200026894-a4ebcd64-d002-4c9d-ba42-614af686dd0a.png">

---

- jitouch 2.82.0
- firefox 102.3.0 ESR
- macOS 11.6.8

**Comment by aaronkollasch** [comment]
Hello,

Do you have "Swipe between pages" enabled in System Preferences > Trackpad > More Gestures? It looks like Firefox picks up on that even if you have the three-finger swipe disabled.

Specifically, enabling the swipe between pages gesture sets this variable:
```shell
defaults write "Apple Global Domain" "AppleEnableSwipeNavigateWithScrolls" '1'
```

And setting swipe navigation to two-finger-only sets these variables, but perhaps Firefox is ignoring them.
```shell
defaults write "com.apple.driver.AppleBluetoothMultitouch.trackpad" "TrackpadThreeFingerHorizSwipeGesture" '0'
defaults write "com.apple.driver.AppleBluetoothMultitouch.trackpad" "TrackpadThreeFingerVertSwipeGesture" '0'
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerVertSwipeGesture" '0'
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerHorizSwipeGesture" '0'
```

So fixing this probably requires a change to Firefox.

**Comment by samcarter** [comment]
I have all options in "More Gestures" disabled:

<img width="780" alt="Screenshot 2022-11-04 at 20 22 49" src="https://user-images.githubusercontent.com/43832342/200058480-138c5766-b429-45e2-a137-7fd9e5ac1180.png">

For experimentation, I tried

- to enabled the option "swipe between full screen apps" with three fingers in system preferences and this will work in firefox. 
- also tried with the MagicPrefs app and this allows to remap three finger swipes with firefox (but I would hate to go back to MagicPrefs as jitouch is much better at picking up gestures)

**Comment by aaronkollasch** [comment]
I found the culprit, Firefox is excluded from the three-finger swipe, probably because it has that gesture built in, so we might get double gestures otherwise. Not sure what the best way is to make that configurable.

https://github.com/aaronkollasch/jitouch/blob/96d199b110cf0919bc6363c5b37bce2b5f2fc63a/jitouch/Jitouch/Gesture.m#L1614-L1642

**Comment by samcarter** [comment]
@aaronkollasch Thank you so much for looking into this! I guess I'll have to train myself to use some other gesture...

**Comment by samcarter** [comment]
@aaronkollasch  Thanks again for digging up the relevant code lines. I've now build a custom version from source without the if-case and now jitouch also works fabulously with firefox! Thank you for your work on this project - this makes my life and probably the life of many other users so much easier!

**Comment by aaronkollasch** [comment]
No problem, I'm glad to hear you got it working for you!

**Comment by EugeneTarasenko** [comment]
> @aaronkollasch Thanks again for digging up the relevant code lines. I've now build a custom version from source without the if-cases and now jitouch also works fabulously with firefox for me! Thank you for your work on this project - this makes my life and probably the life of many other users so much easier!

Does it work with Safari too? Or only with Firefox?

**Comment by samcarter** [comment]
@EugeneTarasenko Yes, it works in Safari, too. 

These are the changes I made: https://github.com/samcarter/Jitouch/commit/8d263f0ae81c3ba12ac94e1bea05cae38f19ea6f
