### ISSUE TITLE
Gestures triggered twice

### ISSUE THREAD

**Issue by Nomad347** [aaronkollasch/jitouch#46]
Mainly for tip tap gestures and swipe. Two finders/3finger clicks work fine. Checked to make sure only one process running

https://justpaste.it/2mcsx

**Comment by aaronkollasch** [comment]
What version of Jitouch and macOS are you using? Also, how did you check that only one process was running?

The log you sent is a bit long, could you clear the logs and restart Jitouch, then reproduce the issue. And set the logging mode to Debug temporarily.

Thanks

**Comment by Nomad347** [comment]
Running macOS Ventura and jitouch 2.82.0
launchctl list | grep Jitouch
1252	0	com.jitouch.Jitouch.agent

log below

**Comment by aaronkollasch** [comment]
Are you also using a Magic Trackpad?
Device 112 should be your Magic Mouse, and device 129 should be a Magic Trackpad 2.

Then again, the repeated gestures are both on device 1 so I don't think it's a case of registering the callback twice for the same device.

Had you seen this issue before macOS Ventura?

**Comment by aaronkollasch** [comment]
Hey, I've made a pull request that might fix this issue, if the problem is that Jitouch adds a callback twice for the same device. Can you try out the debug build below and let me know how it goes? I don't have a Magic Mouse to test with, so If you can send similar logs as before, that would be great.

[Install-Jitouch.pkg.zip](https://github.com/aaronkollasch/jitouch/files/9993844/Install-Jitouch.pkg.zip)

**Comment by Nomad347** [comment]
Issue seems to have gone. I'll keep testing over the weekend and close ticket
log attached
https://justpaste.it/cbbkg

Can't thank you enough for keeping this project alive
have a nice weekend

**Comment by aaronkollasch** [comment]
Great! I've linked the pull request to this issue, so this issue will close automatically when I merge the changes.

Does everything work as expected if you turn the magic mouse off and on again? Or restart Jitouch with the mouse off and then turn it on?

Thanks for reporting.

**Comment by Nomad347** [comment]
restarted machine a few times. App works correctly now. Enabling and disabling in pref pane works correct
