### ISSUE TITLE
how to add custom Keyboard Shortcut with gestures for trackpad?

### ISSUE THREAD

**Issue by yohanyoyo** [aaronkollasch/jitouch#48]
unable to add or even type anything inside of keyboard shortcut input box, is it even possible to add custom shortcuts? I wanted to attach open new tab shortcut (which is CMD + T) with tap Four-Finger Tap gesture for trackpad, even after multiple tries I am unable to add any shortcut. After selecting Four-Finger Tap gesture, I clicked on Keyboard Shortcut input box and pressed CMD + T which didn't do anything, I am unable to type or add any gesture to it. Any suggestions?

**Comment by aaronkollasch** [comment]
Sounds like the preference pane isn't able to watch for keyboard shortcuts. Have you allowed System Preferences in the Security -> Privacy -> Accessibility menu? Or, if it's already present, remove it and then reopen the Jitouch preference pane, then check the box in the Accessibility menu again.

**Comment by yohanyoyo** [comment]
Accessibility menu already allowed, but still nothing, did what you asked but it did not work. Only paste seems to work CMD+V, I am unable to type or add any kind of shortcut. 
Anything else I can do here?

**Comment by aaronkollasch** [comment]
What Jitouch version and macOS version are you using?

**Comment by yohanyoyo** [comment]
macOS Monterey
Version 12.5.1

jitouch 2
Version 2.82.0

**Comment by yohanyoyo** [comment]
removed all permission, uninstalled and installed again. Worked, Finally

**Comment by aaronkollasch** [comment]
Great! Sorry the accessibility permissions can be finicky sometimes.
