### ISSUE TITLE
Version 2.31b doesn't work with Magic Mouse 2; possible simple fix?

### ISSUE THREAD

**Issue by joaofrgomes** [aaronkollasch/jitouch#60]
Hi! I would love to be able to use my Magic Mouse 2 with vintage PowerPC Macs that support multitouch gestures, such as the iBook G4, with version 2.31b.

I know this version is pretty much unsupported as of now, but it is the only one that seems to run on PPC/10.5.8, and possibly under Sorbet Leopard. Could there be any kind of fix that might make it recognize a Magic Mouse 2? Thanks!

**Comment by aaronkollasch** [comment]
I don't know the extent of the differences between the current version and 2.31b. The earliest public release (https://github.com/sukolsak/jitouch) has an OS target of OS X 10.9, so it may take a bunch of work to convert to support Sorbet Leopard, not just a recompile for PPC. 

On the other hand, the way the code recognizes the magic mouse is by checking the device familyID, see https://github.com/sukolsak/jitouch/blob/913c8384a87db95c1ce3bfc20c06a00a0a863737/jitouch/Jitouch/Gesture.m#L2550 and https://github.com/JitouchApp/Jitouch/blob/f8e8d6713f6c71c0af037feb6406bb990c47d5c7/jitouch/Jitouch/Gesture.m#L39-L41

It seems that Magic Mouse 1 and 2 share the same familyID, so if your Jitouch doesn't support Magic Mouse 2, it may be a limitation in the system itself.
