### ISSUE TITLE
Application Windows gesture not working

### ISSUE THREAD

**Issue by skidevil91** [aaronkollasch/jitouch#61]
Was just forced to upgrade to Ventura 13.2.1 and was worried it would break Jitouch like in previous OS upgrades.
Thankfully that doesn't seem to be the case, and Jitouch actually seems to be working more consistently!
BUT, for some reason I can't get the "Application Windows" gesture to work.
I have Jitouch 2.82.1 installed. 
Here are some things I've tried:

1. Setting "Applications Windows" as the action for a trackpad gesture
2. Setting "Applications Windows" as the action for a magic mouse gesture
3. Changing a gesture that works for a different action (such as show desktop) to be the gesture for "Application Windows"

Hoping you are able to help and that this is an easy fix, as this is the main gesture I use with my magic mouse and the one that has kept me tied (and reliant on!) Jitouch all these years.

Thank you for your help.

**Comment by skidevil91** [comment]
Quick update - after finding and reading through #55 just now I was hoping that reverting to 2.82.0 would work (I had previously been using 2.74), but I'm still getting the same result (i.e., "Application Windows" gesture not working).

And to clarify, Jitouch as a whole IS working as other gestures do work.

@aaronkollasch @crazor tagging you for hopes of help.

Thank you for all your continued work on this!

**Comment by aaronkollasch** [comment]
Yeah, I just tried and "Application Windows" is not working, while other gestures such as "Show Desktop" or "Mission Control" still work.

This could be a similar problem to #47, in which the core dock notification is no longer supported, but I checked in Dock.app and it looks like the `com.apple.expose.front.awake` string is still present, and other notifications such as `com.apple.expose.awake` (Mission Control) still work. So I'm not sure what makes "Application Windows" different.

In any case, you could try defining a keyboard shortcut for "Application windows" in System Settings > Keyboard > Mission Control, then mapping your gesture to that shortcut. That works for me.

**Comment by skidevil91** [comment]
Defining keyboard shortcut and then mapping gesture to that works for me. Once again, THANK YOU for your genius and continued support.
