### ISSUE TITLE
Only characters work as gestures

### ISSUE THREAD

**Issue by hadjisoteriou** [aaronkollasch/jitouch#68]
Hey hey. Firstly, thank you for Jitouch. I'm glad to get a version that even runs on Ventura.

Now, I've successfully installed it on a freshly [Ventura] updated MacBook and Jitouch runs well. The characters all work as normal as before but all the trackpad gestures do not ! Have you experienced this before ? Any advice please ? 

Thank you

**Comment by aaronkollasch** [comment]
Hello,

That's strange that character gestures don't work but trackpad gestures do. 
What model of MacBook is it? Can you share your log file from `~/Library/Logs/com.jitouch.Jitouch.log`?

**Comment by hadjisoteriou** [comment]
> Hello,
> 
> 
> 
> That's strange that character gestures don't work but trackpad gestures do. 
> 
> What model of MacBook is it? Can you share your log file from `~/Library/Logs/com.jitouch.Jitouch.log`?

Hey @aaronkollasch 

Apologies - I've just checked which version it's running in the system preferences and it's still showing the older version (2.71). So I'm just attempting to get the latest installed 2.82.1 to run instead ! Thank you

**Comment by hadjisoteriou** [comment]
🙏🏾 I followed these instructions from the other thread [#55](https://github.com/JitouchApp/Jitouch/issues/55#issuecomment-1372108947) and that sorted it of course. Seemed as though those character gestures that were working still were running on that previous version and I had assumed it had launched 2.82.1 after the install ! Such a simple fix 😬 all working now. thank you for your work and hope I didn't waste too much of your time ! 🙏🏾

**Comment by aaronkollasch** [comment]
Great! Glad you got it sorted out.
