### ISSUE TITLE
It's still version 2.75 in about tab

### ISSUE THREAD

**Issue by bindiry** [aaronkollasch/jitouch#7]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/104797/143815016-373ee197-9b5a-47da-961f-523371f4c0a2.png">

I installed the version 2.77

but still show up 2.75 in about tab, I wondered if I had installed the latest version.

Thank you for the modified version.

**Comment by aaronkollasch** [comment]
Thanks for the heads up, this will be fixed in the next version.
