### ISSUE TITLE
Move/resize causes jiitouch to crash on Sonoma (14.4.1)

### ISSUE THREAD

**Issue by Shotgunosine** [aaronkollasch/jitouch#80]
Just updated to Sonoma (14.4.1). The move/resize gesture works but if I stay in the move/resize state too long, jiitouch crashes and I have to force quit the process from the activity monitor. I can move/resize if I'm very quick about it though. I'm on a 2019 Intel MacBook Pro. I didn't see any obvious error messages in the console associated with the crash.

**Comment by Shotgunosine** [comment]
Whoops, I see this was fixed in 2.8.1. I updated and this seems to be resolved.

**Comment by henrymazza** [comment]
@Shotgunosine I got the same issue here, but I don't get what 2.8.1 means, the latest release is [Jitouch 2.82.1](https://github.com/JitouchApp/Jitouch/releases/tag/v2.82.1), is this what you mean? If so this is the exactly one I got but it still crashes! 🤔

**Comment by Shotgunosine** [comment]
Yep, sorry, 2.82.1. I upgraded to that and it works for me now. Are you sure you're using the new version? When you click about on the Jitouch panel in system preferences does it show 2.82.1?
